// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmBHuwoZC5JERx4AAUFa_ZULwMkMSA-AU',
    appId: '1:608967414741:web:64b243cafca338009b235c',
    messagingSenderId: '608967414741',
    projectId: 'taswaq-9e149',
    authDomain: 'taswaq-9e149.firebaseapp.com',
    storageBucket: 'taswaq-9e149.appspot.com',
    measurementId: 'G-KRG82W3DGX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-LrSbF9ASomfS_1IaVJWNLR85waRypK0',
    appId: '1:608967414741:android:61682c3ad2be49879b235c',
    messagingSenderId: '608967414741',
    projectId: 'taswaq-9e149',
    storageBucket: 'taswaq-9e149.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-qGrSyJZFegscxuaQHhghbSlZwc5_sP4',
    appId: '1:608967414741:ios:30d0e90fe0fd07b59b235c',
    messagingSenderId: '608967414741',
    projectId: 'taswaq-9e149',
    storageBucket: 'taswaq-9e149.appspot.com',
    androidClientId: '608967414741-gh0jtfs94nc1bifnntj5o7vdaki7t8gl.apps.googleusercontent.com',
    iosClientId: '608967414741-v8vrjg4lhq4ori6ndm556o5vmnuelkom.apps.googleusercontent.com',
    iosBundleId: 'com.example.taswaqDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-qGrSyJZFegscxuaQHhghbSlZwc5_sP4',
    appId: '1:608967414741:ios:30d0e90fe0fd07b59b235c',
    messagingSenderId: '608967414741',
    projectId: 'taswaq-9e149',
    storageBucket: 'taswaq-9e149.appspot.com',
    androidClientId: '608967414741-gh0jtfs94nc1bifnntj5o7vdaki7t8gl.apps.googleusercontent.com',
    iosClientId: '608967414741-v8vrjg4lhq4ori6ndm556o5vmnuelkom.apps.googleusercontent.com',
    iosBundleId: 'com.example.taswaqDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmBHuwoZC5JERx4AAUFa_ZULwMkMSA-AU',
    appId: '1:608967414741:web:57334febf508b9649b235c',
    messagingSenderId: '608967414741',
    projectId: 'taswaq-9e149',
    authDomain: 'taswaq-9e149.firebaseapp.com',
    storageBucket: 'taswaq-9e149.appspot.com',
    measurementId: 'G-WW7VR9Z1M3',
  );
}
